apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperledger-fabric.fullname" . }}-crypto-config
  labels:
    app.kubernetes.io/name: {{ include "hyperledger-fabric.chart" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app: {{ include "hyperledger-fabric.name" . }}
    chart: {{ include "hyperledger-fabric.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: crypto-config
data: 
  crypto-config.yaml: |-
    OrdererOrgs:
    - Name: Orderer
      Domain: example.com
      Specs:
      - Hostname: orderer
    PeerOrgs:
    - Name: Org1
      Domain: org1.example.com
      EnableNodeOUs: true
      Template:
        Count: 5
      Users:
        Count: 5
    - Name: Org2
      Domain: org2.example.com
      EnableNodeOUs: true
      Template:
        Count: 5
      Users:
        Count: 5